### ISSUE TITLE
Implement incomes and expenses charts

### ISSUE THREAD

**Issue by vieiraeduardos** [euodeionomedeusuario/mamom-project#2]
I have to implement a way to show all incomes and expenses in a chart.

What is best chart? @sebastiaohns

1. Line chart
2. Bar chart (I think it is  better!)
3. Pizza chart

**Comment by sebastiaohns** [comment]
bar chart

why are you speaking in english?

2018-04-16 13:06 GMT-03:00 Eduardo Vieira <notifications@github.com>:

**Comment by vieiraeduardos** [comment]
É o recomendado! :)
